{% set name = "django-ninja" %}
{% set version = "0.16.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-ninja-{{ version }}.tar.gz
  sha256: 288f44d183df4543040a660e7bc236b5aed50c4f1fb332fcdd7f3c9fd59a7f86

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - django >=2.0.13
    - pydantic >=1.6,<1.9
    - python >=3.6
    - python-tzdata

test:
  commands:
    - python -c "from django.conf import settings; settings.configure(DEBUG=True); import ninja; import ninja.compatibility"
    - pip check
  requires:
    - pip

about:
  home: https://django-ninja.rest-framework.com
  dev_url: https://github.com/vitalik/django-ninja
  summary: Django Ninja - Fast Django REST framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
