{% set name = "django-ninja" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 590bb1c8fc32f07bac1d5b5d404419205c41b4945b86d4237b0676174c1b6df7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python {{ python_min }}
  run:
    - django >=3.1
    - pydantic >=2.0,<3.0.0
    - python >={{ python_min }}

test:
  commands:
    - python -c "from django.conf import settings; settings.configure(DEBUG=True); import ninja; import ninja.compatibility"
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://django-ninja.rest-framework.com
  dev_url: https://github.com/vitalik/django-ninja
  summary: Django Ninja - Fast Django REST framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
