{% set name = "django-ninja" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 757197b5e238d4ac2256ecf1a7d8f5c1883e1890ad154f2f38ee7d7ed687b9a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python >=3.7
  run:
    - django >=3.1
    - pydantic >=2.0,<3.0.0
    - python >=3.7

test:
  commands:
    - python -c "from django.conf import settings; settings.configure(DEBUG=True); import ninja; import ninja.compatibility"
    - pip check
  requires:
    - pip

about:
  home: https://django-ninja.rest-framework.com
  dev_url: https://github.com/vitalik/django-ninja
  summary: Django Ninja - Fast Django REST framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
