{% set name = "django-ninja" %}
{% set version = "0.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-ninja-{{ version }}.tar.gz
  sha256: e8b9edfa731580d49bdd85dc12570bb48bfbad4f2fb97218d00496b470ec5830

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - django >=2.2
    - pydantic >=1.6,<2.0.0
    - python >=3.6
    - python-tzdata

test:
  commands:
    - python -c "from django.conf import settings; settings.configure(DEBUG=True); import ninja; import ninja.compatibility"
    - pip check
  requires:
    - pip

about:
  home: https://django-ninja.rest-framework.com
  dev_url: https://github.com/vitalik/django-ninja
  summary: Django Ninja - Fast Django REST framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
