schema_version: 1

context:
  name: django-ninja
  version: "1.4.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 7433e587f41c82f7eb961bc0196e2b1ba9445f3d30b7f01c8412708598633c35

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python ${{ python_min }}.*
  run:
    - django >=3.1
    - pydantic >=2.0,<3.0.0
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - "python -c \"from django.conf import settings; settings.configure(DEBUG=True); import ninja; import ninja.compatibility\""
      - pip check

about:
  summary: Django Ninja - Fast Django REST framework
  license: MIT
  license_file: LICENSE
  homepage: https://django-ninja.rest-framework.com
  repository: https://github.com/vitalik/django-ninja

extra:
  recipe-maintainers:
    - thewchan
